[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 19200
lib_deps =
    2dom/PxMatrix LED MATRIX library@^1.8.2
    me-no-dev/ESPAsyncWebServer
    me-no-dev/ESPAsyncTCP
    bblanchon/ArduinoJson
    adafruit/RTClib
    adafruit/Adafruit GFX Library

[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino
monitor_speed = 19200
lib_deps =
    2dom/PxMatrix LED MATRIX library@^1.8.2
    me-no-dev/ESPAsyncWebServer
    me-no-dev/ESPAsyncTCP
    bblanchon/ArduinoJson
    adafruit/RTClib
    adafruit/Adafruit GFX Library

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 19200
lib_deps =
    2dom/PxMatrix LED MATRIX library@^1.8.2
    me-no-dev/ESPAsyncWebServer
    me-no-dev/AsyncTCP
    bblanchon/ArduinoJson
    adafruit/RTClib
    adafruit/Adafruit GFX Library
